# Setup
title: Dialektika
tagline: ""
description: Opravdová moudrost je v poznání vlastní nedokonalosti &mdash; Sókratés
url: https://dialektika.cz
baseurl: ""
paginate: 5
permalink: pretty
excerpt_separator: "<!-- more -->"

# About/contact
author:
  name: Jaroslava Krejčí & Jan B. Krejčí
  url: https://dialektika.cz
  email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: _#UA-XXXX-Y

months:
  - "ledna"
  - "února"
  - "března"
  - "dubna"
  - "května"
  - "června"
  - "července"
  - "srpna"
  - "září"
  - "října"
  - "listopadu"
  - "prosince"
